let modelos = 'sedan'

switch (modelos){
    case 'hatch':
        console.log('Compra efetuada com sucesso')
        break
    case 'sedan':
        console.log('Tem certeza que não prefere o modelo hatch?')
        break
    case 'motocicletas':
        console.log('Tem certeza que não prefere o modelo hatch?')
        break
    case 'caminhonetes':
        console.log('Tem certeza que não prefere o modelo hatch?')
    default:
        console.log('Não trabalhamos com esse modelo')

}